package frc.robot.subsystems.drive;

import static edu.wpi.first.units.Units.DegreesPerSecond;
import static edu.wpi.first.units.Units.Second;
import static edu.wpi.first.units.Units.Volts;

import java.util.List;
import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.hardware.Pigeon2;

import com.ctre.phoenix6.swerve.SwerveRequest;
import com.ctre.phoenix6.swerve.SwerveRequest.ApplyFieldSpeeds;
import com.ctre.phoenix6.swerve.SwerveRequest.ApplyRobotSpeeds;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;

import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.commands.PathfindingCommand;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Transform2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.geometry.Translation3d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.util.Units;

import edu.wpi.first.units.measure.AngularVelocity;
import edu.wpi.first.util.sendable.Sendable;
import edu.wpi.first.util.sendable.SendableBuilder;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;

import frc.robot.subsystems.VisionSubsystem;
import frc.robot.subsystems.drive.DriveConstants.TunerSwerveDrivetrain;
import frc.robot.subsystems.manipSubsystems.SpitterSubsystem;
import frc.robot.utilities.LimelightHelpers;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */

public class DriveSubsystem extends TunerSwerveDrivetrain implements Subsystem {

    public final static Field2d field = new Field2d();
    
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;
    
    private static Transform2d SPITTER_OFFSET = new Transform2d(0, Units.inchesToMeters(-10), Rotation2d.k180deg);
    
    public boolean hubAlign = false;
    public boolean isAimed = false;
    
    public double distanceToTarget; 
    
    private Translation2d currentTarget = DriveConstants.BLUE_HUB_CENTER;
    private double targetAngleRot;
    private double currentAngleRot;
    
    private Sendable driveSendable;
    
    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;
    
    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();
    
    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );
    
    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
	private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
    * SysId routine for characterizing rotation.
    * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
    * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
    */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );
    
    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;
        
    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public DriveSubsystem(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        SmartDashboard.putData("Field", field);

        setupPathPlanner();
    }
    
    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public DriveSubsystem(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        driveSendable = new Sendable() {
            @Override 
            public void initSendable(SendableBuilder builder) {
                builder.addDoubleProperty("PoseX", () -> getPose().getX(), null);
                builder.addDoubleProperty("PoseY", () -> getPose().getY(), null);
                builder.addBooleanProperty("Align to Hub", () -> hubAlign, null);
                builder.addBooleanProperty("Is Aimed", () -> isAimed, null);
                builder.addDoubleProperty("Distance from hub", () -> distanceToTarget, null);
                builder.addDoubleProperty("TargetX", () -> currentTarget.getX(), null);
                builder.addDoubleProperty("TargetY", () -> currentTarget.getY(), null);
                builder.addDoubleProperty("TargetRot", () -> targetAngleRot, null);
                builder.addDoubleProperty("CurrentRot", () -> currentAngleRot, null);
            }
        };
        SmartDashboard.putData("Drive", driveSendable);
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
            * Periodically try to apply the operator perspective.
            * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
            * This allows us to correct the perspective in case the robot code restarts mid-match.
            * Otherwise, only check and apply the operator perspective if the DS is disabled.
            * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
            */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }

        distanceFromHub();

        if (hubAlign) {
            // overrides velocity on the z axis to align to the hub
            Pose2d currentPose = getPose(); 
            ChassisSpeeds currentSpeed = getState().Speeds;
            
            Translation2d robotTranslation = currentPose.getTranslation();
            Translation2d spitterTranslation = robotTranslation.rotateBy(Rotation2d.k180deg); // our spitter is on the back of the bot
                
            Translation2d botVelocity = 
                new Translation2d(
                    currentSpeed.vxMetersPerSecond,
                    currentSpeed.vyMetersPerSecond
                );
                
            Translation2d tangentialVelocity = 
                new Translation2d(
                    -currentSpeed.omegaRadiansPerSecond * SPITTER_OFFSET.getY(),
                    currentSpeed.omegaRadiansPerSecond * SPITTER_OFFSET.getX()
                );
            
            Translation2d effectiveShooterVelocity = botVelocity.plus(tangentialVelocity);
            Translation2d virtualTarget = getTargetTranslation();
            currentTarget = virtualTarget;

            // measures distance to our target in meters
            double predictedDistance = spitterTranslation.getDistance(virtualTarget);

            // time of flight, includes mechanical/system latency
            double timeOfFlight = getToF(predictedDistance) + SpitterSubsystem.SYSTEM_LATENCY_SECONDS;

            // calculate the distance the ball will drift
            Translation2d predictedOffset = effectiveShooterVelocity.times(timeOfFlight);

            // Shifts aim to be ahead of drift
            virtualTarget = virtualTarget.minus(predictedOffset);

            // Set distance for use in other commands
            distanceToTarget = robotTranslation.getDistance(virtualTarget);

            /* Calculate needed angle to target */
            double targetAngleRad = Math.atan2(
                virtualTarget.getY() - robotTranslation.getY(),
                virtualTarget.getX() - robotTranslation.getX()
            );

            targetAngleRad += Math.PI; // trying to get back of bot to face forwards
            
            targetAngleRot = targetAngleRad / (2 * Math.PI);

            double currentAngleRad = currentPose.getRotation().getRadians();

            currentAngleRot = currentAngleRad / (2 * Math.PI);

            double angularSpeedRps = DriveConstants.rotationPID.calculate(currentAngleRad, targetAngleRad);
            
            // will finish if the bot is correctly facing target
            isAimed = DriveConstants.rotationPID.atSetpoint();	
            
            // overrides the drivers Z input with the calculated angle 
            ChassisSpeeds driverSpeed = currentSpeed;
            ChassisSpeeds newVelocity = new ChassisSpeeds(driverSpeed.vxMetersPerSecond, driverSpeed.vyMetersPerSecond, angularSpeedRps);
            SwerveRequest fieldSpeedRequest = new ApplyFieldSpeeds().withSpeeds(newVelocity);
            // running the bot in robot relative with the new calculated angle
            applyRequest(() -> fieldSpeedRequest);
        }
    }

    public void postTrajectoryToField(List<Pose2d> trajectory) {
        field.getObject("Trajectory").setPoses(trajectory);
    }

    public double getToF(double distanceMeters) {
        return SpitterSubsystem.SPITTER_MAP.get(distanceMeters).timeOfFlight();
    }

    /**
    * Updates the drivetrain odometry object to the robot's current position on the
    * field.
    * 
    * @return The new updated pose of the robot.
    */
    public void updateOdometry() {
        for (String side : new String[] {"left", "right"}) {
            LimelightHelpers.SetRobotOrientation(
                "limelight-" + side, getIMUYaw().getDegrees(), 
                getIMUYawRate().in(DegreesPerSecond), 
                0, 0, 0, 0
            );

            LimelightHelpers.PoseEstimate estimate = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-" + side);

            if (estimate != null && estimate.tagCount > 0) {
                Translation3d aprilTagPosition = LimelightHelpers.getTargetPose3d_RobotSpace("limelight-" + side).getTranslation();

                if (Math.hypot(aprilTagPosition.getX(), aprilTagPosition.getZ()) <= 3.5) {			
                    addVisionMeasurement(new Pose2d(estimate.pose.getX(), estimate.pose.getY(), getIMUYaw()), estimate.timestampSeconds);
                }
            }
        }
    }

    public void zeroGyro() {
        getIMU().setYaw(0);
        resetOdometry(new Pose2d(getPose().getX(), getPose().getY(), new Rotation2d()));
    }

    public Command zeroGyroCommand() {
        return runOnce(() -> zeroGyro());
    }

    public void redGyro() {
        getIMU().setYaw(0);
        resetOdometry(new Pose2d(getPose().getX(), getPose().getY(), new Rotation2d(Math.PI)));
    }

    /**
     * Zeros the gyro with the lime light based on 2d april tags
     */

    public Command zeroGyroWithLimelight() {
        return runOnce(
            () -> {
                Rotation2d mt1_left = VisionSubsystem.getMT1Rotation("left");
                Rotation2d mt1_right = VisionSubsystem.getMT1Rotation("right");

                if (mt1_left != null && mt1_right == null) {
                    setIMUYaw(mt1_left);
                } else if (mt1_right != null && mt1_left == null) {
                    setIMUYaw(mt1_right);
                } else if (mt1_left != null && mt1_right != null) {
                    Rotation2d average = new Rotation2d(
                        Math.atan2(
                            Math.sin(mt1_left.getRadians()) + Math.sin(mt1_right.getRadians()),
                            Math.cos(mt1_left.getRadians()) + Math.cos(mt1_right.getRadians())
                        )
                    );
                    setIMUYaw(average);
                }
            }
        );
    }

    /**
     * Resets odometry to the given pose. Gyro angle and module positions do not
     * need to be reset when calling this
     * method. However, if either gyro angle or module position is reset, this must
     * be called in order for odometry to
     * keep working..
     * @param initialHolonomicPose The pose to set the odometry to
     */

    public void resetOdometry(Pose2d pose) {
        if (DriverStation.getAlliance().get().equals(DriverStation.Alliance.Red)) {
            if (pose == null) {
                resetPose(DriveConstants.startingRedPose);
                return;
            }
        } else if (DriverStation.getAlliance().get().equals(DriverStation.Alliance.Blue)) {
            if (pose == null) {
                resetPose(DriveConstants.startingBluePose);
                return;
            }
        } else {
            System.out.println("Unknown/incorrect alliance setup");
        }

        resetPose(pose);
    }

    /**
     * Gets the current pose (position and rotation) of the robot, as reported by
     * odometry.
     *
     * @return The robot's pose
     */	

    public Pose2d getPose() {
        return getStateCopy().Pose;
    }

    public void setIMUYaw(Rotation2d yaw) {
        getIMU().setYaw(yaw.getMeasure());
        resetOdometry(new Pose2d(getPose().getX(), getPose().getY(), yaw));
    }

    public Pigeon2 getIMU() {
        return getPigeon2();
    }

    public Rotation2d getIMUYaw() {
        return getIMU().getRotation2d();
    }

    public AngularVelocity getIMUYawRate() {
        return getIMU().getAngularVelocityZWorld().getValue();
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public Command toggleHubAlign() {
		return new Command() {
			@Override
			public void initialize() {
				hubAlign = true;
			}

			@Override
			public void end(boolean interrupted) {
				hubAlign = false;
			}
		};
	}

    /**Takes the robots pose and selects a target based on where it is.
	 * Walks through your logic and sees if you are in the center field or the alliance zone then selects a target.
	 * @return Selected target Translation
	 */

	public Translation2d getTargetTranslation() {
		Pose2d robotPose = getPose();
		if (DriverStation.getAlliance().get().equals(DriverStation.Alliance.Red)) {
			if (robotPose.getMeasureX().gt(DriveConstants.RED_HUB_CENTER.getMeasureX())) {
				return DriveConstants.RED_HUB_CENTER;
			}

			if (robotPose.getMeasureY().gt(DriveConstants.CENTER_FIELD_Y)) {
				return DriveConstants.RED_TARGET_LEFT;
			}	
			return DriveConstants.RED_TARGET_RIGHT;
		}
		
		if (robotPose.getMeasureX().lt(DriveConstants.BLUE_HUB_CENTER.getMeasureX())) {
			return DriveConstants.BLUE_HUB_CENTER;
		}

		if (robotPose.getMeasureY().gt(DriveConstants.CENTER_FIELD_Y)){
			return DriveConstants.BLUE_TARGET_LEFT;
		}
		return DriveConstants.BLUE_TARGET_RIGHT;
	}

	//Returns the angle from the robot to the hub (in radians)
	public double angleFromHub() {
		Translation2d hubPose = getTargetTranslation();
		return Math.atan2(hubPose.getY() - getPose().getY(), hubPose.getX() - getPose().getX());
	}
	
	//Returns the distance from the robot to the hub 
	private double distanceFromHub() {
		return getPose().getTranslation().getDistance(getTargetTranslation());
	}

	public void setupPathPlanner() {
		RobotConfig config;

		try {
			config = RobotConfig.fromGUISettings();

            final boolean enableFeedforward = true;

            AutoBuilder.configure(
                () -> getPose(),
                this::resetOdometry,
                () -> getKinematics().toChassisSpeeds(),
                (speedsRobotRelative, moduleFeedForwards) -> {
                    ApplyRobotSpeeds relativeRequest = new ApplyRobotSpeeds().withSpeeds(speedsRobotRelative);
					if (enableFeedforward) {
                        relativeRequest
                            .withWheelForceFeedforwardsX(moduleFeedForwards.linearForces())
                            .withWheelForceFeedforwardsY(moduleFeedForwards.linearForces());
                            applyRequest(() -> relativeRequest);
					} else {
						applyRequest(() -> relativeRequest);
					}
				},
				new PPHolonomicDriveController(
					DriveConstants.PP_TRANS,
					DriveConstants.PP_ROT
				),
				config,
				() -> DriverStation.getAlliance().get().equals(DriverStation.Alliance.Red),
				this
            );
			PathfindingCommand.warmupCommand().schedule();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
