package frc.robot.subsystems.drive;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.StatusCode;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.hardware.Pigeon2;
import com.ctre.phoenix6.mechanisms.swerve.LegacySwerveRequest.ApplyChassisSpeeds;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.ctre.phoenix6.swerve.SwerveRequest.ApplyFieldSpeeds;
import com.ctre.phoenix6.swerve.SwerveRequest.FieldCentric;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Transform2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.geometry.Translation3d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.kinematics.Odometry;
import edu.wpi.first.math.kinematics.SwerveDriveKinematics;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.units.measure.AngularVelocity;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotBase;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import com.ctre.phoenix6.swerve.SwerveRequest.ApplyFieldSpeeds;


import frc.robot.subsystems.drive.DriveConstants.TunerSwerveDrivetrain;
import frc.robot.subsystems.manipSubsystems.SpitterSubsystem;
import frc.robot.utilities.LimelightHelpers;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class DriveSubsystem extends TunerSwerveDrivetrain implements Subsystem {
    public final DriveSubsystem drivetrain = DriveConstants.createDrivetrain();

    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

	private static Transform2d SPITTER_OFFSET = new Transform2d(0, Units.inchesToMeters(-10), Rotation2d.k180deg);

	public boolean hubAlign = false;
	public boolean isAimed = false;

	public double distanceToTarget; 

	private Translation2d currentTarget = DriveConstants.BLUE_HUB_CENTER;
	private double targetAngleRot;
	private double currentAngleRot;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public DriveSubsystem(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public DriveSubsystem(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }
    
    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public DriveSubsystem(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }

        if (hubAlign) {
			// overrides velocity on the z axis to align to the hub
			Pose2d currentPose = drivetrain.getPose(); 
			ChassisSpeeds currentSpeed = drivetrain.getKinematics().toChassisSpeeds();
			
			Translation2d robotTranslation = currentPose.getTranslation();
			Translation2d spitterTranslation = robotTranslation.rotateBy(Rotation2d.k180deg); // our spitter is on the back of the bot
				
			Translation2d botVelocity = 
				new Translation2d(
					currentSpeed.vxMetersPerSecond,
					currentSpeed.vyMetersPerSecond
				);
				
			Translation2d tangentialVelocity = 
				new Translation2d(
					-currentSpeed.omegaRadiansPerSecond * SPITTER_OFFSET.getY(),
					currentSpeed.omegaRadiansPerSecond * SPITTER_OFFSET.getX()
				);
			
			Translation2d effectiveShooterVelocity = botVelocity.plus(tangentialVelocity);
			Translation2d virtualTarget = getTargetTranslation();
			currentTarget = virtualTarget;

			// measures distance to our target in meters
			double predictedDistance = spitterTranslation.getDistance(virtualTarget);

			// time of flight, includes mechanical/system latency
			double timeOfFlight = getToF(predictedDistance) + SpitterSubsystem.SYSTEM_LATENCY_SECONDS;

            // calculate the distance the ball will drift
            Translation2d predictedOffset = effectiveShooterVelocity.times(timeOfFlight);

            // Shifts aim to be ahead of drift
            virtualTarget = virtualTarget.minus(predictedOffset);

            // Set distance for use in other commands
            distanceToTarget = robotTranslation.getDistance(virtualTarget);

            /* Calculate needed angle to target */
            double targetAngleRad = Math.atan2(
                virtualTarget.getY() - robotTranslation.getY(),
                virtualTarget.getX() - robotTranslation.getX()
            );

            targetAngleRad += Math.PI; // trying to get back of bot to face forwards
            
            targetAngleRot = targetAngleRad / (2 * Math.PI);

            double currentAngleRad = currentPose.getRotation().getRadians();

            currentAngleRot = currentAngleRad / (2 * Math.PI);

            double angularSpeedRps = DriveConstants.rotationPID.calculate(currentAngleRad, targetAngleRad);
            
            // will finish if the bot is correctly facing target
            isAimed = DriveConstants.rotationPID.atSetpoint();	
            
            // overrides the drivers Z input with the calculated angle 
            ChassisSpeeds driverSpeed = currentSpeed;
            ChassisSpeeds newVelocity = new ChassisSpeeds(driverSpeed.vxMetersPerSecond, driverSpeed.vyMetersPerSecond, angularSpeedRps);
            ApplyFieldSpeeds fieldSpeeds = new ApplyFieldSpeeds().withSpeeds(newVelocity);
            // running the bot in robot relative with the new calculated angle
            drivetrain.applyRequest(fieldSpeeds);
		}
    }

    public double getToF(double distanceMeters) {
		return SpitterSubsystem.SPITTER_MAP.get(distanceMeters).timeOfFlight();
	}

    /**
    * Updates the drivetrain odometry object to the robot's current position on the
    * field.
    * 
    * @return The new updated pose of the robot.
    */
	public void updateOdometry() {
		for (String side : new String[] {"left", "right"}) {
			LimelightHelpers.SetRobotOrientation(
				"limelight-" + side, getIMUYaw().getDegrees(), 
				getIMUYawRate().in(DegreesPerSecond), 
				0, 0, 0, 0
			);

			LimelightHelpers.PoseEstimate estimate = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-" + side);

			if (estimate != null && estimate.tagCount > 0) {
				Translation3d aprilTagPosition = LimelightHelpers.getTargetPose3d_RobotSpace("limelight-" + side).getTranslation();

				if (Math.hypot(aprilTagPosition.getX(), aprilTagPosition.getZ()) <= 3.5) {			
					drivetrain.addVisionMeasurement(new Pose2d(estimate.pose.getX(), estimate.pose.getY(), getIMUYaw()), estimate.timestampSeconds);
					//TODO: in order to switch to a different drive we need to change this
					// create a SwervePoseEstimator and use the .addVisionMeasurment(with same stuff here) on it
				}
			}
		}
    }

    /**
	 * Resets odometry to the given pose. Gyro angle and module positions do not
	 * need to be reset when calling this
	 * method. However, if either gyro angle or module position is reset, this must
	 * be called in order for odometry to
	 * keep working..
	 * @param initialHolonomicPose The pose to set the odometry to
	 */
	public void resetOdometry(Pose2d pose) {
		if (DriverStation.getAlliance().get().equals(DriverStation.Alliance.Red)) {
            if (pose == null) {
                drivetrain.resetOdometry(DriveConstants.startingRedPose);
                return;
            }
        } else if (DriverStation.getAlliance().get().equals(DriverStation.Alliance.Blue)) {
            if (pose == null) {
				drivetrain.resetOdometry(DriveConstants.startingBluePose);
				return;
			}
        } else {
			System.out.println("Unknown/incorrect alliance setup");
		}

        drivetrain.resetOdometry(pose);
		// TODO: simply steal the yagsl code that makes this (if no CTRE alternative)
    }

    /**
	 * Gets the current pose (position and rotation) of the robot, as reported by
	 * odometry.
	 *
	 * @return The robot's pose
	 */	
	public Pose2d getPose() {
		return drivetrain.getPose();
	}

    public void setIMUYaw(Rotation2d yaw) {
		getIMU().setYaw(yaw.getMeasure());
		drivetrain.resetOdometry(new Pose2d(getPose().getX(), getPose().getY(), yaw));
	}

	public Pigeon2 getIMU() {
		return drivetrain.getPigeon2();
	}

	public Rotation2d getIMUYaw() {
		return getIMU().getRotation2d();
	}

	public AngularVelocity getIMUYawRate() {
		return getIMU().getAngularVelocityZWorld().getValue();
	}

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public Command toggleHubAlign() {
		return new Command() {
			@Override
			public void initialize() {
				hubAlign = true;
			}

			@Override
			public void end(boolean interrupted) {
				hubAlign = false;
			}
		};
	}
    /**Takes the robots pose and selects a target based on where it is.
	 * Walks through your logic and sees if you are in the center field or the alliance zone then selects a target.
	 * @return Selected target Translation
	 */
	public Translation2d getTargetTranslation() {
		Pose2d robotPose = getPose();
		if(DriverStation.getAlliance().get().equals(DriverStation.Alliance.Red)) {
		
			if(robotPose.getMeasureX().gt(RED_HUB_CENTER.getMeasureX())) {
				return RED_HUB_CENTER;
			}
			if(robotPose.getMeasureY().gt(CENTER_FIELD_Y)) {
				return RED_TARGET_LEFT;
			}	
			return RED_TARGET_RIGHT;

		}
		
		if(robotPose.getMeasureX().lt(BLUE_HUB_CENTER.getMeasureX())) {
			return BLUE_HUB_CENTER;
		}
		if(robotPose.getMeasureY().gt(CENTER_FIELD_Y)){
			return BLUE_TARGET_LEFT;
		}
		return BLUE_TARGET_RIGHT;
	}

	/*
	* Returns the angle from the robot to the hub (in radians)
	*/
	public double angleFromHub() {
		Translation2d hubPose = getTargetTranslation();
		return Math.atan2(hubPose.getY() - getPose().getY(), hubPose.getX() - getPose().getX());
	}
	
	/*
	* Returns the distance from the robot to the hub 
	*/
	private double distanceFromHub() {
		return getPose().getTranslation().getDistance(getTargetTranslation());
	}
	
}
