package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.hardware.Pigeon2;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.ctre.phoenix6.swerve.SwerveRequest.ApplyFieldSpeeds;
import com.pathplanner.lib.config.PIDConstants;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.ProfiledPIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Transform2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.geometry.Translation3d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.trajectory.TrapezoidProfile.Constraints;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.units.measure.AngularAcceleration;
import edu.wpi.first.units.measure.AngularVelocity;
import edu.wpi.first.units.measure.Distance;
import edu.wpi.first.units.measure.LinearAcceleration;
import edu.wpi.first.units.measure.LinearVelocity;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;

import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.subsystems.manipSubsystems.SpitterSubsystem;
import frc.robot.utilities.LimelightHelpers;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();
    
    private static final Distance TRANS_ERR_TOL = Meters.of(0.025);
	private static final LinearVelocity TRANS_VEL_TOL = MetersPerSecond.of(0.1);
	private static final Angle ROT_ERR_TOL = Degrees.of(0.5);
	private static final AngularVelocity ROT_VEL_TOL = DegreesPerSecond.of(0.5);

	private static final LinearVelocity TRANS_MAX_VEL = MetersPerSecond.of(3);
	private static final LinearAcceleration TRANS_MAX_ACCEL = MetersPerSecondPerSecond.of(2);

	private static final AngularVelocity ROT_MAX_VEL = DegreesPerSecond.of(540);
	private static final AngularAcceleration ROT_MAX_ACCEL = DegreesPerSecondPerSecond.of(540);

    private static final Pose2d startingBluePose = new Pose2d(2, 4, new Rotation2d(0));
    private static final Pose2d startingRedPose = new Pose2d(2, 4, new Rotation2d(Math.PI));

	public static final Translation2d BLUE_HUB_CENTER = new Translation2d(4.6116, 4.0213);
	public static final Translation2d BLUE_HUB_BACK = new Translation2d(5.2342, 4.0213);

	public static final Translation2d RED_HUB_CENTER = new Translation2d(11.9014, 4.0213);
	public static final Translation2d RED_HUB_BACK = new Translation2d(11.3044, 4.0213);

	public static final Translation2d RED_TARGET_LEFT = new Translation2d(16.54048, 5.101844);
	public static final Translation2d RED_TARGET_RIGHT = new Translation2d(16.54048 ,1.266444);
	
	public static final Translation2d BLUE_TARGET_LEFT = new Translation2d(0,5.101844);
	public static final Translation2d BLUE_TARGET_RIGHT = new Translation2d(0,1.266444);
	
    public static final Transform2d SPITTER_OFFSET = new Transform2d(0, Units.inchesToMeters(-10), Rotation2d.k180deg);

	public static final Distance CENTER_FIELD_Y = Meters.of(4.021328);

	public boolean hubAlign = false;
	public boolean isAimed = false;

	public boolean squareUp = false;

	public boolean relativeMode = false;

	public double distanceToTarget; 

	private Translation2d currentTarget = BLUE_HUB_CENTER;
	private double targetAngleRot;
	private double currentAngleRot;

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

	// Standard PID
    private static final PIDConstants TRANSLATION_CONSTANTS =
		new PIDConstants(
			5.5,
			0.2,
			0.1
		);

	private static final PIDConstants ROTATION_CONSTANTS =
		new PIDConstants(
			3.4,
			0.0,
			0.3
		);

    // Pathplanner PID
	private static final PIDConstants PP_TRANS = 
		new PIDConstants(
			5.2,
			0.0,
			0.01
		);

	private static final PIDConstants PP_ROT = 
		new PIDConstants(
			3.0,
			0.0,
			0.0
		);

	/**
	 * Estaablishes PID for X axis
	 */
    private ProfiledPIDController xTranslationPID = new ProfiledPIDController(
        TRANSLATION_CONSTANTS.kP,
        TRANSLATION_CONSTANTS.kI,
        TRANSLATION_CONSTANTS.kD,
		new Constraints(TRANS_MAX_VEL.in(MetersPerSecond), TRANS_MAX_ACCEL.in(MetersPerSecondPerSecond))
    );
	/**
	 * Establishes the PID for the y axis
	 */
	private ProfiledPIDController yTranslationPID = new ProfiledPIDController(
        TRANSLATION_CONSTANTS.kP,
        TRANSLATION_CONSTANTS.kI,
        TRANSLATION_CONSTANTS.kD,
		new Constraints(TRANS_MAX_VEL.in(MetersPerSecond), TRANS_MAX_ACCEL.in(MetersPerSecondPerSecond))
    );

	/**
 	* Establishing PID for the rotational axis
 	*/
    private ProfiledPIDController rotationPID = new ProfiledPIDController(
		ROTATION_CONSTANTS.kP,
		ROTATION_CONSTANTS.kI,
		ROTATION_CONSTANTS.kD,
		new Constraints(ROT_MAX_VEL.in(RadiansPerSecond), ROT_MAX_ACCEL.in(RadiansPerSecondPerSecond))
	);

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }

        
		updateOdometry();
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    } 

    
public void setIMUYaw(Rotation2d yaw) {
		getPigeon2().setYaw(yaw.getMeasure());
		resetAllianceOdometry(new Pose2d(getPose().getX(), getPose().getY(), yaw));
	}

	public Rotation2d getIMUYaw() {
		return getPigeon2().getRotation2d();
	}

	public AngularVelocity getIMUYawRate() {
		return getPigeon2().getAngularVelocityZWorld().getValue();
	}


	public void updateOdometry() {

		for (String side : new String[] {"left", "right"}) {

			LimelightHelpers.SetRobotOrientation(
				"limelight-" + side, getIMUYaw().getDegrees(), 
				getIMUYawRate().in(DegreesPerSecond), 
				0, 0, 0, 0
			);

			LimelightHelpers.PoseEstimate estimate = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-" + side);

			if (estimate != null && estimate.tagCount > 0) {

				Translation3d aprilTagPosition = LimelightHelpers.getTargetPose3d_RobotSpace("limelight-" + side).getTranslation();

				if (Math.hypot(aprilTagPosition.getX(), aprilTagPosition.getZ()) <= 3.5) {
					
					addVisionMeasurement(new Pose2d(estimate.pose.getX(), estimate.pose.getY(), getIMUYaw()), estimate.timestampSeconds);

				}
					
			}

		}

    }

    public void resetAllianceOdometry(Pose2d pose) {
		if (DriverStation.getAlliance().get().equals(DriverStation.Alliance.Red)) {
            if (pose == null) {
                
                resetPose(startingRedPose);
                return;
            }
        } else if (DriverStation.getAlliance().get().equals(DriverStation.Alliance.Blue)) {
            if (pose == null) {
				resetPose(startingBluePose);
				return;
			}
        } else {
			System.out.println("Unknown/incorrect alliance setup");
		}

        resetPose(pose);
    }

	public Command driveFieldOriented(Supplier<ChassisSpeeds> velocity) {
		return run(() -> {
			if (hubAlign) {
				// overrides velocity on the z axis to align to the hub
				Pose2d currentPose = getPose();
				ChassisSpeeds currentSpeed = getStateCopy().Speeds;
				
				Translation2d robotTranslation = currentPose.getTranslation();
				Translation2d spitterTranslation = robotTranslation.rotateBy(Rotation2d.k180deg); // our spitter is on the back of the bot
				
				Translation2d botVelocity = 
					new Translation2d(
						currentSpeed.vxMetersPerSecond,
						currentSpeed.vyMetersPerSecond
					);
				
				Translation2d tangentialVelocity = 
					new Translation2d(
						-currentSpeed.omegaRadiansPerSecond * SPITTER_OFFSET.getY(),
						currentSpeed.omegaRadiansPerSecond * SPITTER_OFFSET.getX()
					);
				
				Translation2d effectiveShooterVelocity = botVelocity.plus(tangentialVelocity);
				Translation2d virtualTarget = getStateCopy().Pose.getTranslation();//getTargetTranslation();
				currentTarget = virtualTarget;

				// measures distance to our target in meters
				double predictedDistance = spitterTranslation.getDistance(virtualTarget);

				// time of flight, includes mechanical/system latency
				double timeOfFlight = getToF(predictedDistance) + SpitterSubsystem.SYSTEM_LATENCY_SECONDS;

				// calculate the distance the ball will drift
				Translation2d predictedOffset = effectiveShooterVelocity.times(timeOfFlight);

				// Shifts aim to be ahead of drift
				virtualTarget = virtualTarget.minus(predictedOffset);

				// Set distance for use in other commands
				distanceToTarget = robotTranslation.getDistance(virtualTarget);

				/* Calculate needed angle to target */
				double targetAngleRad = Math.atan2(
					virtualTarget.getY() - robotTranslation.getY(),
					virtualTarget.getX() - robotTranslation.getX()
				);

				targetAngleRad += Math.PI; // trying to get back of bot to face forwards
				
				targetAngleRot = targetAngleRad / (2 * Math.PI);

				double currentAngleRad = currentPose.getRotation().getRadians();

				currentAngleRot = currentAngleRad / (2 * Math.PI);

				double angularSpeedRps = rotationPID.calculate(currentAngleRad, targetAngleRad);
				
				// will finish if the bot is correctly facing target
				isAimed = rotationPID.atSetpoint();	
				
				// overrides the drivers Z input with the calculated angle 
				ChassisSpeeds driverSpeed = velocity.get();
				ChassisSpeeds newVelocity = new ChassisSpeeds(driverSpeed.vxMetersPerSecond, driverSpeed.vyMetersPerSecond, angularSpeedRps);
				
				// running the bot in robot relative with the new calculated angle
				drive(ChassisSpeeds.fromFieldRelativeSpeeds(newVelocity, getIMUYaw()));
			} else if (squareUp) {

				Pose2d currentPose = getPose();

				double currentAngleRot = currentPose.getRotation().getRotations();

				double targetAngleRot = Math.round(currentAngleRot * 4) / 4;

				double angularSpeedRps = rotationPID.calculate(currentAngleRot * 2 * Math.PI, targetAngleRot * 2 * Math.PI);
								
				// overrides the drivers Z input with the calculated angle 
				ChassisSpeeds driverSpeed = velocity.get();
				ChassisSpeeds newVelocity = new ChassisSpeeds(driverSpeed.vxMetersPerSecond, driverSpeed.vyMetersPerSecond, angularSpeedRps);
				
				// running the bot in robot relative with the new calculated angle
				drive(ChassisSpeeds.fromFieldRelativeSpeeds(newVelocity, getIMUYaw()));

			} else if (relativeMode) {
				distanceToTarget = distanceFromHub();
				if(DriverStation.getAlliance().get().equals(DriverStation.Alliance.Red)) {
					drive(velocity.get().times(-1)); // will invert on red
				} else {
					drive(velocity.get());
				}
			} else {
				distanceToTarget = distanceFromHub(); 
				drive(ChassisSpeeds.fromFieldRelativeSpeeds(velocity.get(), getIMUYaw()));
				// driveFieldOriented(velocity.get()); //Field relative is relying on odemtry instead of IMUYaw
			}
		}).ignoringDisable(false);
	}

    public double getToF(double distanceMeters) {
        return SpitterSubsystem.SPITTER_MAP.get(distanceMeters).timeOfFlight();
    }

    public Pose2d getPose() {
        return getStateCopy().Pose;
    }

    public void drive(ChassisSpeeds velocity) {
        applyRequest(() -> new ApplyFieldSpeeds().withSpeeds(velocity));
    }

    	public Translation2d getTargetTranslation() {
		Pose2d robotPose = getPose();
		if (DriverStation.getAlliance().get().equals(DriverStation.Alliance.Red)) {
			if (robotPose.getMeasureX().gt(RED_HUB_CENTER.getMeasureX())) {
				return RED_HUB_CENTER;
			}

			if (robotPose.getMeasureY().gt(CENTER_FIELD_Y)) {
				return RED_TARGET_LEFT;
			}	
			return RED_TARGET_RIGHT;
		}

		if (robotPose.getMeasureX().lt(BLUE_HUB_CENTER.getMeasureX())) {
			return BLUE_HUB_CENTER;
		}

		if (robotPose.getMeasureY().gt(CENTER_FIELD_Y)){
			return BLUE_TARGET_LEFT;
		}
		return BLUE_TARGET_RIGHT;
	}

    //Returns the distance from the robot to the hub 
	private double distanceFromHub() {
		return getPose().getTranslation().getDistance(getTargetTranslation());
	}


}

